### ISSUE TITLE
The given key was not present in the dictionary error while trying to bring up dialog from form

### ISSUE THREAD

**Issue by paul198204** [BotBuilderCommunity/botbuilder-community-dotnet#148]
I am seeing the below error while trying to shop up dialog from form during completion

```
The given key was not present in the dictionary 
   at Bot.Builder.Community.Dialogs.FormFlow.FormDialog`1.<MessageReceived>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bot.Builder.Community.Dialogs.FormFlow.FormDialog`1.<ContinueDialogAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<ContinueDialogAsync>d__21.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.<ContinueDialogAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<ContinueDialogAsync>d__21.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

**Comment by v-kydela** [comment]
@paul198204 - Can you provide some repro steps?

**Comment by paul198204** [comment]
I provided the sample as you requested. Steps: Start the app, sent any text to bot and provide answers to bot questions. you should see failure. Basically I am trying to display dialog on closing of the form in the same which is supported in V3 with Context.Call. Please let me know if you need any info.

**Comment by v-kydela** [comment]
@paul198204 - I've found the problem with your bot, and I'll get to that. But it looks like there is a problem with the FormFlow package after all, and there's arguably even a problem with the SDK.

## The problem with the SDK

[ComponentDialog.cs](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs#L194) consistently tries to access `PersistedDialogState` without checking if the key is present in the active dialog's state. It assumes the key is present because it's assigned to in `ComponentDialog.BeginDialogAsync`, but that method can be overridden and the key can be deleted.

## The problem with the FormFlow package

`FormDialog<T>` is an example of a class that extends `ComponentDialog` and overrides `BeginDialogAsync` without calling the base implementation. Interestingly, [it looks like the base implementation was called at one point and then commented out](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Dialogs.FormFlow/FormDialog.cs#L262):

```c#
//var result = await base.BeginDialogAsync(outerDc, options, cancellationToken);
```

This means `PersistedDialogState` in never created in the dialog instance, and so if any of the `ComponentDialog` methods try to access it they will throw the error "The given key was not present in the dictionary." Since it looks like `FormDialog<T>` doesn't use its inner dialog set, it should probably just extend `Dialog` instead of `ComponentDialog`.

## The problem with your bot

You are trying to begin a new dialog in your form's `OnCompletion` delegate. This new dialog will be added to the stack on top of the form dialog because the `OnCompletion` delegate gets called just before the form dialog ends. The form dialog tries to end itself by calling `DialogContext.EndDialogAsync` which then ends your new dialog instead of the form dialog and then tries to resume the form dialog. Resuming the form dialog calls `ComponentDialog.RepromptDialogAsync` which tries to access `PersistedDialogState` which throws the error you're seeing.

Hopefully you can see from this that you should not be starting a new dialog from within the `OnCompletion` delegate. Just retrieve the result of the form dialog first and then start the new dialog after the form dialog has ended. If you would like to learn more about how to use the Bot Framework, please refer to our extensive documentation: https://docs.microsoft.com/en-us/azure/bot-service
