### ISSUE TITLE
How to integrate Bot.Builder.Community.Adapters.Alexa with Microsoft Bot Dialog?

### ISSUE THREAD

**Issue by C0d1ngJammer** [BotBuilderCommunity/botbuilder-community-dotnet#231]
Hello there,

iam trying to integrate Amazon Alexa to my Microsoft Bot Builder Dialog and found the "Bot.Builder.Community.Adapters.Alexa" Adapter.
There are two things which makes it difficult for me to create an working App:
	I only can get Alexa working without the Dialog mechanism
	It does not seem to work for multiple Endpoints (Bot-Emulator and Alexa --> See Question below)

I have tried it a couple of times with different approaches but with no success:
	Only Bot-Emulator is working, Alexa creates a NullPointer
	Dialog working with bot and Alexa, but session values did not get saved (shouldEndSessionFalse was set to false..not the problem)
	...

Could you please create a demo which shows us how to do archive that?
I would prefer an example with the "19.custom-dialogs"-Demo (which I used for my tests).
That might be faster than using my disgusting code :)

I dont care if it uses .NET Core MVC or .NET Core (non-MVC).

Another Question:
Can you run the "Bot-Emulator" and the Alexa with one Application-Session, in other words with 2 Endpoints or is it not designed for that?
Can you have your .net core bot framework application listen on multiple endpoints (e.g. "Bot-Emulator" and Alexa) or do I need to run two different (with same Dialog-Logic) Programs?

Yet another thing I dont unserstand is why the microsoft Teams Adapter is using ActivityHandler and this one uses the Adapter(?)?

I would love to hear from you!
Thanks alot - Keep on Working.

- C0d1ngJammer

**Comment by arafattehsin** [comment]
@C0d1ngJammer - Too many questions 🙂 but thank you for asking and I appreciate your time. I'd love to re-direct you to our [latest sample for Alexa](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/feature/adopt-alexadotnet/samples/Alexa%20Adapter%20Sample
) queries. This branch is still WIP unless it gets merged to the master therefore I won't recommend it for production use. 

Please let me know if it resolves your Alexa issue. 

To answer your Adapter vs ActivityHandler query, I'd request you to watch this [video](https://channel9.msdn.com/Shows/AI-Show/Bot-Framework--Using-custom-adapters-to-surface-your-bot-anywhere-Part-3-of-3?term=AI%20Show&lang-en=true) and let me know if you have got any questions.  :)

**Comment by C0d1ngJammer** [comment]
@arafattehsin Okay, so now Iam getting everthing working - Thanks!
Alexa and Bot-Emulator are both working with one instance running.

Just had to reference the libs "Bot.Builder.Community.Adapters.Alexa" and "Bot.Builder.Community.Adapters.Alexa" manually from the .../libraries folder and added some parts of the "19.custom-dialogs"-Project.

So the "latest sample for Alexa"-Branche seems to work with the dialog part, I couldn't get the the offical sample "Alexa Adapter Sample" in develop branche to work with my code snippets.
404 errors because it could not find the endpoint or exceptions like:
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Bot.Builder.Community.Adapters.Alexa.AlexaAdapter.CreateResponseFromLastActivity(IEnumerable`1 activities, ITurnContext context)
   at Bot.Builder.Community.Adapters.Alexa.AlexaAdapter.ProcessActivity(AlexaRequestBody alexaRequest, BotCallbackHandler callback)
   at Bot.Builder.Community.Adapters.Alexa.AlexaAdapter.ProcessActivity(AlexaRequestBody alexaRequest, BotCallbackHandler callback)
   at Bot.Builder.Community.Adapters.Alexa.Integration.AspNet.Core.AlexaHttpAdapter.ProcessAsync(HttpRequest httpRequest, HttpResponse httpResponse, IBot bot, CancellationToken cancellationToken)
   at AlexaAdapterSample.Controllers.AlexaController.PostAsync() in C:\Users\manuk\Downloads\botbuilder-community-dotnet-develop\botbuilder-community-dotnet-develop\samples\AlexaAdapterSample\Controllers\AlexaController.cs:line 31
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`


I have read that the  .NET Core MVC is going to be obsolet at some point and that  .NET Core (non-MVC) is going to be the prefered way. Is this the case?

Will this branche you showed me be published at some point or is it just experimental?

-Manuel

**Comment by arafattehsin** [comment]
Hi @C0d1ngJammer - I am glad that it worked for you. Regarding the latest exceptions, we will get back to you but I wanted to learn where did you read about .NET MVC being obsoleted? Can you point me to that link.

To answer your last question as when the Alexa Adopt branch will be published: soon (the date isn't decided yet but it won't be too long from today).

**Comment by C0d1ngJammer** [comment]
Hey @arafattehsin - Thank you for your support!

Sorry - I understood following wrong:
"...current plan is to drop the support for ASP.NET Web API. This decision was made as we don’t believe that the Web API integration is widely used and this would be a good opportunity for us to reduce our surface area..."
https://www.garypretty.co.uk/2019/12/02/bot-builder-community-alexa-adapter-update-preview/ 

Which has nothing to do with what I said.

And some of the links are dead e.g. AlexaIntentRequestToMessageActivityMiddleware, AlexaRequestToMessageEventActivitiesMiddleware (see site). But I think that is off topic.

Currently Iam developing my experimental project with the above mentioned branche and it works very well. This is just a hobby and my first microsoft-Bot application. It might take a while for me :).


-Manuel
