### ISSUE TITLE
unable to launch request using Dotnet core

### ISSUE THREAD

**Issue by Webrusterkk** [BotBuilderCommunity/botbuilder-community-dotnet#54]
Following the Same Process using the DotNet core 2.2 , unable to create an Invocation.

```
POST http://xxxxx.azurewebsites.net/api/skillrequests application/json; charset=utf-8 2934
2019-03-11 12:37:01.989 +00:00 [Error] Microsoft.BotBuilderSamples.BasicBot: Exception caught : System.MissingMethodException: Method not found: 'Void Microsoft.Bot.Schema.ConversationAccount..ctor(System.Nullable`1<Boolean>, System.String, System.String, System.String, System.String, System.String)'.
   at Bot.Builder.Community.Adapters.Alexa.AlexaAdapter.RequestToActivity(AlexaRequestBody skillRequest)
   at Bot.Builder.Community.Adapters.Alexa.AlexaAdapter.<ProcessActivity>d__8.MoveNext()
2019-03-11 12:37:02.049 +00:00 [Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLL62M5F1KSE", Request id "0HLL62M5F1KSE:00000006": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.BotBuilderSamples.Startup.<>c__DisplayClass6_1.<<ConfigureServices>b__6>d.MoveNext() in D:\Kishore\Projects\Bot_dotnet\Startup.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bot.Builder.Community.Adapters.Alexa.AlexaAdapter.<ProcessActivity>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bot.Builder.Community.Adapters.Alexa.Integration.AspNet.Core.AlexaRequestHandler.<ProcessMessageRequestAsync>d__4.MoveNext()
```

**Comment by garypretty** [comment]
Hi.

Any chance you can zip your bot code and send me a link and I'll take a look for you?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Webrusterkk** [comment]
Hey @garypretty  , I have mailed (gary@garypretty.co.uk) you the code .

Thanks in advance.

**Comment by garypretty** [comment]
@Webrusterkk Hi. Got your code.  Any chance you could zip the entire project including the project / solution files?  I ideally need to be able to open -> run so that I can point an alexa skill at it so I can see what is happening.

**Comment by Webrusterkk** [comment]
@garypretty  Done, I send a mail, which includes total project.

**Comment by garypretty** [comment]
@Webrusterkk Thanks - its not come through yet, but I will keep an eye out. Is it from wetransfer again?

**Comment by Webrusterkk** [comment]
@garypretty  Yes, Using Wetransfer only. I think you should be able to get by now .. Let me know if you haven't received it. will see other ways to send you the code

**Comment by garypretty** [comment]
@Webrusterkk I was able to replicate your error locally.  I have swapped out the NuGet package for the local Alexa adapter project which I have updated to 4.3 and it is working as expected 👍 I will be getting a new Alexa package out to NuGet later today all being well, so you should be able to test with the updated package shortly.

**Comment by Webrusterkk** [comment]
@garypretty  that sounds great , Gary !! thanks for the Prompt reply ..

**Comment by garypretty** [comment]
@Webrusterkk Hi. The updated package is now available on NuGet - give this a go and let me know how you get on 👍  https://www.nuget.org/packages/Bot.Builder.Community.Adapters.Alexa/1.0.237

**Comment by Webrusterkk** [comment]
@garypretty  Yes!! its working as intended.. thanks for your time.. i really appreciate your help

**Comment by Webrusterkk** [comment]
@garypretty  Sure.. Just Let us know When its out .. will give it a ride ..
